services:
  dige_sylius_tinypng_plugin.menu.tinypng_menu_listener:
    class: Dige\TinypngPlugin\EventListener\MenuListener
    public: true
    tags:
      - { name: kernel.event_listener, method: buildMenu, event: sylius.menu.admin.main }
