dige_sylius_tinypng_plugin_settings:
  path: /admin/tinypng/settings
  methods: [POST, GET]
  defaults:
    _controller: dige.sylius.tinypng.plugin.controller.settings:settingsAction
    _sylius:
      section: admin
      template: "@DigeSyliusTinypngPlugin/Settings/index.html.twig"

dige_sylius_tinypng_plugin_media_log_load_all:
  path: /admin/tinypng/settings/media_log/load
  methods: [POST]
  defaults:
    _controller: dige.sylius.tinypng.plugin.controller.settings:loadMediaAction
    _sylius:
      section: admin

dige_sylius_tinypng_plugin_setting_counts:
  path: /admin/tinypng/settings/counts
  methods: [GET]
  defaults:
    _controller: dige.sylius.tinypng.plugin.controller.settings:getInProgressCountsAction
    _sylius:
      section: admin
