imports:
  - { resource: services/controller.yml }
  - { resource: services/messages.yml }
  - { resource: services/admin_menu.yml }
  - { resource: services/compress.yml }
  - { resource: services/listeners.yml }
  - { resource: services/form.yml }
  - { resource: services/service.yml }
